# Generated by Django 5.2.5 on 2025-08-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(help_text='Authentication token for Whisk API', max_length=500)),
                ('project_id', models.CharField(help_text='Default project ID for Whisk API', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Whisk Settings',
                'verbose_name_plural': 'Whisk Settings',
            },
        ),
    ]
