# Generated by Django 5.2.5 on 2025-08-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_generator', '0002_whisksettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkimagerequest',
            name='title',
            field=models.CharField(default='Untitled Bulk Generation', help_text='Name/title for this bulk generation', max_length=200),
        ),
    ]
