# Generated by Django 5.2.5 on 2025-08-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_generator', '0003_bulkimagerequest_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFXSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(help_text='Authentication token for ImageFX API', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ImageFX Settings',
                'verbose_name_plural': 'ImageFX Settings',
            },
        ),
        migrations.AddField(
            model_name='bulkimagerequest',
            name='api_provider',
            field=models.CharField(choices=[('whisk', 'Whisk'), ('imagefx', 'ImageFX')], default='whisk', help_text='API provider used for generation', max_length=20),
        ),
        migrations.AddField(
            model_name='imageprompt',
            name='api_provider',
            field=models.CharField(choices=[('whisk', 'Whisk'), ('imagefx', 'ImageFX')], default='whisk', help_text='API provider used for generation', max_length=20),
        ),
        migrations.AlterField(
            model_name='bulkimagerequest',
            name='title',
            field=models.CharField(help_text='Name/title for this bulk generation', max_length=200),
        ),
    ]
